# Generated by Django 5.2.8 on 2025-11-23 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Место, в котором необходимо выполнять привычку.', max_length=255, verbose_name='Место')),
                ('time', models.TimeField(help_text='Время, когда необходимо выполнять привычку (например, 14:30:00).', verbose_name='Время')),
                ('action', models.CharField(help_text='Действие, которое представляет собой привычка.', max_length=255, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, help_text='Если True, это приятная привычка, которая может быть вознаграждением для полезной.', verbose_name='Признак приятной привычки')),
                ('reward', models.CharField(blank=True, help_text='Текстовое вознаграждение, если нет связанной приятной привычки.', max_length=255, null=True, verbose_name='Вознаграждение')),
                ('periodicity', models.PositiveSmallIntegerField(default=1, help_text='Интервал повторения привычки (от 1 до 7 дней).', verbose_name='Периодичность (в днях)')),
                ('time_to_complete', models.PositiveSmallIntegerField(help_text='Время, которое предположительно потратит пользователь (не более 120 секунд).', verbose_name='Время на выполнение (в секундах)')),
                ('is_public', models.BooleanField(default=False, help_text='Если True, привычка отображается в общем списке.', verbose_name='Признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, help_text='Приятная привычка, которая выполняется сразу после полезной.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(help_text='Создатель привычки', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
                'ordering': ('time', 'id'),
            },
        ),
    ]
